---
repos:
  - repo: https://github.com/UCL-MIRSG/.github
    rev: v0.200.0
    hooks:
      - id: mirsg-hooks

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
