[project]
name = "zarr_benchmarks"
version = "0.0.1"
authors = [
  { name="Centre for Advanced Research Computing", email="arc.collaborations@ucl.ac.uk" },
]
description = "zarr benchmarks"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE"}

dependencies = [
    "zarr",
    "imageio",
    "pyperf"
]

[project.urls]
Homepage = "https://github.com/HEFTIEProject/zarr-benchmarks"
Issues = "https://github.com/HEFTIEProject/zarr-benchmarks/issues"