[project]
authors = [
    {email = "arc.collaborations@ucl.ac.uk", name = "Centre for Advanced Research Computing"},
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "imageio",
    "matplotlib",
    "pandas",
    "pytest",
    "pytest-benchmark",
    "seaborn",
    "zarr",
]
description = "zarr benchmarks"
license = {file = "LICENSE"}
name = "zarr_benchmarks"
readme = "README.md"
requires-python = ">=3.11"
version = "0.0.1"

[project.optional-dependencies]
dev = [
    "pre-commit",
]

[project.urls]
Homepage = "https://github.com/HEFTIEProject/zarr-benchmarks"
Issues = "https://github.com/HEFTIEProject/zarr-benchmarks/issues"
