[project]
authors = [
    {email = "arc.collaborations@ucl.ac.uk", name = "Centre for Advanced Research Computing"},
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "imageio",
    "pytest",
    "pytest-benchmark",
    "tensorstore",
    "tox",
    "zarr",
]
description = "zarr benchmarks"
license = {file = "LICENSE"}
name = "zarr_benchmarks"
readme = "README.md"
requires-python = ">=3.11"
version = "0.0.1"

[project.optional-dependencies]
dev = [
    "pre-commit",
]

[project.urls]
Homepage = "https://github.com/HEFTIEProject/zarr-benchmarks"
Issues = "https://github.com/HEFTIEProject/zarr-benchmarks/issues"

# override sorting inline arrays for tox configuration - otherwise 'commands' lines are sorted and broken
[tool.tomlsort]
overrides."tool.tox.*".inline_arrays = false

[tool.tox]
env_list = ["py313-zarrv2", "py313-zarrv3"]
requires = ["tox>=4.24"]

[tool.tox.env.py313-zarrv2]
commands = [["pytest", "--benchmark-save=zarr-python-v2", "--benchmark-save-data", {extend = true, replace = "posargs"}]]
deps = ["zarr==2.18.4", "numcodecs==0.15.1"]
description = "Run benchmarks under zarr-python version 2"

[tool.tox.env.py313-zarrv3]
commands = [["pytest", "--benchmark-save=zarr-python-v3", "--benchmark-save-data", {extend = true, replace = "posargs"}]]
deps = ["zarr==3.0.6", "numcodecs==0.15.1"]
description = "Run benchmarks under zarr-python version 3"
