env_list = ["py313-zarrv2", "py313-zarrv3", "py313-tensorstore"]
requires = ["tox>=4.24"]

[env.py313-tensorstore]
commands = [
    [
        "pytest",
        "--benchmark-save=tensorstore",
        "--benchmark-save-data",
        "-m",
        "tensorstore",
        {extend = true, replace = "posargs"},
    ],
]
description = "Run benchmarks under tensorstore"
extras = ["tensorstore"]

[env.py313-zarrv2]
commands = [
    [
        "pytest",
        "--benchmark-save=zarr-python-v2",
        "--benchmark-save-data",
        "-m",
        "zarr_python",
        {extend = true, replace = "posargs"},
    ],
]
description = "Run benchmarks under zarr-python version 2"
extras = ["zarr-python-v2"]

[env.py313-zarrv3]
commands = [
    [
        "pytest",
        "--benchmark-save=zarr-python-v3",
        "--benchmark-save-data",
        "-m",
        "zarr_python",
        {extend = true, replace = "posargs"},
    ],
]
description = "Run benchmarks under zarr-python version 3"
extras = ["zarr-python-v3"]
