env_list = ["py313-zarrv2", "py313-zarrv3", "py313-tensorstore"]
requires = ["tox>=4.24"]

[env.py313-tensorstore]
commands = [
    [
        "pytest",
        "--benchmark-save=tensorstore",
        "--benchmark-save-data",
        "--benchmark-storage=data/json",
        "-m",
        "tensorstore",
        {extend = true, replace = "posargs"},
    ],
]
deps = ["tensorstore==0.1.73"]
description = "Run benchmarks under tensorstore"

[env.py313-zarrv2]
commands = [
    [
        "pytest",
        "--benchmark-save=zarr-python-v2",
        "--benchmark-save-data",
        "--benchmark-storage=data/json",
        "-m",
        "zarr_python",
        {extend = true, replace = "posargs"},
    ],
]
deps = ["zarr==2.18.4", "numcodecs==0.15.1"]
description = "Run benchmarks under zarr-python version 2"

[env.py313-zarrv3]
commands = [
    [
        "pytest",
        "--benchmark-save=zarr-python-v3",
        "--benchmark-save-data",
        "--benchmark-storage=data/json",
        "-m",
        "zarr_python",
        {extend = true, replace = "posargs"},
    ],
]
deps = ["zarr==3.0.6", "numcodecs==0.15.1"]
description = "Run benchmarks under zarr-python version 3"
