---
name: Benchmarks and tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  benchmarks:
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[plots]

      - name: Run benchmarks and tests with tox
        run: |
          tox -- --image=dev --benchmark-storage=data/results/dev --rounds=1 --warmup-rounds=0

      - name: Run plotting script on benchmark output
        run: |
          python src/zarr_benchmarks/create_plots.py

      - name: Run plotting script on example results
        run: |
          python src/zarr_benchmarks/create_plots.py --example_results
